# Generated by Django 5.2.6 on 2025-11-17 17:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_id_alter_productgallery_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewrating',
            unique_together={('product', 'user')},
        ),
    ]
