# Generated by Django 5.2.6 on 2025-11-17 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_reviewrating_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('hide', 'Hidden'), ('show', 'Shown'), ('moderate', 'Moderated')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpfulness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='reviews/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='reviewrating',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='reviewrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='helpful_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='is_verified_purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='moderation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='total_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='status',
            field=models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden'), ('pending', 'Pending Moderation')], default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='reviewrating',
            index=models.Index(fields=['product', 'status', 'created_at'], name='store_revie_product_030d86_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewrating',
            index=models.Index(fields=['user', 'product'], name='store_revie_user_id_9f28c2_idx'),
        ),
        migrations.AddField(
            model_name='reviewaudit',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewaudit',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.reviewrating'),
        ),
        migrations.AddField(
            model_name='reviewhelpfulness',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpfulness_votes', to='store.reviewrating'),
        ),
        migrations.AddField(
            model_name='reviewhelpfulness',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewmedia',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='store.reviewrating'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewhelpfulness',
            unique_together={('review', 'user')},
        ),
    ]
